name: Build Mac

on:
  workflow_dispatch: {}
    
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    environment: master
    steps:
    - uses: actions/checkout@v7
    - name: Restore
      shell: cmd
      run: |
        call "C:\\Program Files\\Microsoft Visual Studio\\18\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
        where clang
        where clang++

        mkdir build
        cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -S . -B build -G Ninja
        cmake --build build
