name: Build Mac

on:
  workflow_dispatch: {}
    
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    environment: master
    steps:
    - uses: actions/checkout@v7
    - name: Restore
      shell: cmd
      run: |
        mkdir build
        cmake -S . -B build -G Ninja
        cmake --build build
